version: '3'
services:
  web:
    image: pass-link-to-container:latest
    ports:
      - "8080:8080"
    environment:
    # angabe customer base url über app <- container-env <- instance-env <- userdata <- cloudformation XXX.id-report.com
    - CONFIG_PAGE=${CUSTOMER_URL}
    # - CONFIG_PAGE=https://google.com