version: '3'
services:
  web:
    image: mcg-redirection-test:latest
    ports:
      - "8081:8081"
    environment:
    # angabe customer base url über app <- container-env <- instance-env <- userdata <- cloudformation XXX.id-report.com
    - CONFIG_PAGE=${CUSTOMER_URL}
    # - CONFIG_PAGE=https://google.com